services:
  app:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"

  extrator:
    build: .
    volumes:
      - ./data:/app/data
    command: python main.py 2024 2026
    restart: "no"